export const INDICES_DESCARGA_INTERNET_INICIO = 'INDICES_DESCARGA_INTERNET_INICIO'
export const INDICES_DESCARGA_INTERNET_EXITO = 'INDICES_DESCARGA_INTERNET_EXITO'
export const INDICES_DESCARGA_INTERNET_ERRO = 'INDICES_DESCARGA_INTERNET_ERRO'
