export const CHECAR_AUTH = 'CHECAR_AUTH'
export const CHECAR_AUTH_EXITO = 'CHECAR_AUTH_EXITO'
export const CHECAR_AUTH_ERRO = 'CHECAR_AUTH_ERRO'

export const PESSOA_DADOS_DESCARGA_INICIO = 'PESSOA_DADOS_DESCARGA_INICIO'
export const PESSOA_DADOS_DESCARGA_EXITO = 'PESSOA_DADOS_DESCARGA_EXITO'
export const PESSOA_DADOS_DESCARGA_ERRO = 'PESSOA_DADOS_DESCARGA_ERRO'
export const PESSOA_DADOS_FILTRADO = 'PESSOA_DADOS_FILTRADO'
export const PESSOA_DADOS_INCLUIR = 'PESSOA_DADOS_INCLUIR'

export const PESSOA_DADOS_INCLUSAO_EXITO = 'PESSOA_DADOS_INCLUSAO_EXITO'
export const PESSOA_DADOS_INCLUSAO_ERRO = 'PESSOA_DADOS_INCLUSAO_ERRO'

export const PESSOA_DADOS_CNPJ_EXITO = 'PESSOA_DADOS_CNPJ_EXITO'
export const PESSOA_DADOS_CNPJ_ERRO = 'PESSOA_DADOS_CNPJ_ERRO'